import { SeverityLevel } from '../types';

export interface LibraryPattern {
  name: string;
  displayName: string;
  description: string;
  type: 'library' | 'framework' | 'protocol' | 'standard';
  docsUrl?: string;
  importPatterns: RegExp[];
  usagePatterns: RegExp[];
  flowType: 'jwt' | 'oauth2' | 'session' | 'webauthn' | 'apikey' | 'basic' | 'unknown';
}

export interface VulnerabilityPattern {
  id: string;
  title: string;
  description: string;
  recommendation: string;
  severity: SeverityLevel;
  owasp?: string;
  cwe?: string;
  pattern: RegExp;
  excludePatterns?: RegExp[];
  references?: string[];
  checkFn?: (fileContent: string, match: RegExpMatchArray) => boolean;
}

export const LIBRARY_PATTERNS: LibraryPattern[] = [
  {
    name: 'jsonwebtoken',
    displayName: 'JSON Web Token (jsonwebtoken)',
    description: 'Industry-standard JWT implementation for Node.js',
    type: 'library',
    docsUrl: 'https://github.com/auth0/node-jsonwebtoken',
    flowType: 'jwt',
    importPatterns: [
      /require\s*\(\s*['"]jsonwebtoken['"]\s*\)/,
      /from\s+['"]jsonwebtoken['"]/,
    ],
    usagePatterns: [
      /jwt\.sign\s*\(/,
      /jwt\.verify\s*\(/,
      /jwt\.decode\s*\(/,
    ],
  },
  {
    name: 'jose',
    displayName: 'JOSE (jose)',
    description: 'Modern JavaScript implementation of JWT, JWK, JWS, JWE',
    type: 'library',
    docsUrl: 'https://github.com/panva/jose',
    flowType: 'jwt',
    importPatterns: [
      /require\s*\(\s*['"]jose['"]\s*\)/,
      /from\s+['"]jose['"]/,
    ],
    usagePatterns: [
      /new\s+SignJWT\s*\(/,
      /jwtVerify\s*\(/,
      /new\s+JWTVerifier\s*\(/,
    ],
  },
  {
    name: 'express-jwt',
    displayName: 'express-jwt',
    description: 'JWT authentication middleware for Express',
    type: 'library',
    docsUrl: 'https://github.com/auth0/express-jwt',
    flowType: 'jwt',
    importPatterns: [
      /require\s*\(\s*['"]express-jwt['"]\s*\)/,
      /from\s+['"]express-jwt['"]/,
    ],
    usagePatterns: [/expressjwt\s*\(/, /jwt\(\s*\{/],
  },
  {
    name: 'passport',
    displayName: 'Passport.js',
    description: 'Authentication middleware for Node.js supporting 500+ strategies',
    type: 'framework',
    docsUrl: 'https://www.passportjs.org',
    flowType: 'oauth2',
    importPatterns: [
      /require\s*\(\s*['"]passport['"]\s*\)/,
      /from\s+['"]passport['"]/,
    ],
    usagePatterns: [
      /passport\.authenticate\s*\(/,
      /passport\.use\s*\(/,
      /passport\.initialize\s*\(/,
      /passport\.session\s*\(/,
    ],
  },
  {
    name: 'passport-google-oauth20',
    displayName: 'Passport Google OAuth 2.0',
    description: 'Passport strategy for Google OAuth 2.0',
    type: 'library',
    docsUrl: 'https://github.com/jaredhanson/passport-google-oauth2',
    flowType: 'oauth2',
    importPatterns: [
      /require\s*\(\s*['"]passport-google-oauth20['"]\s*\)/,
      /from\s+['"]passport-google-oauth20['"]/,
    ],
    usagePatterns: [/new\s+GoogleStrategy\s*\(/],
  },
  {
    name: 'passport-github2',
    displayName: 'Passport GitHub OAuth',
    description: 'Passport strategy for GitHub OAuth',
    type: 'library',
    docsUrl: 'https://github.com/cfsghost/passport-github',
    flowType: 'oauth2',
    importPatterns: [
      /require\s*\(\s*['"]passport-github2?['"]\s*\)/,
      /from\s+['"]passport-github2?['"]/,
    ],
    usagePatterns: [/new\s+GitHubStrategy\s*\(/],
  },
  {
    name: 'next-auth',
    displayName: 'NextAuth.js',
    description: 'Complete authentication solution for Next.js',
    type: 'framework',
    docsUrl: 'https://next-auth.js.org',
    flowType: 'oauth2',
    importPatterns: [
      /require\s*\(\s*['"]next-auth['"]\s*\)/,
      /from\s+['"]next-auth['"]/,
      /from\s+['"]next-auth\/(?:react|providers\/\w+)['"]/,
    ],
    usagePatterns: [
      /NextAuth\s*\(/,
      /getServerSession\s*\(/,
      /useSession\s*\(/,
      /signIn\s*\(/,
    ],
  },
  {
    name: 'express-session',
    displayName: 'express-session',
    description: 'Session middleware for Express',
    type: 'library',
    docsUrl: 'https://github.com/expressjs/session',
    flowType: 'session',
    importPatterns: [
      /require\s*\(\s*['"]express-session['"]\s*\)/,
      /from\s+['"]express-session['"]/,
    ],
    usagePatterns: [
      /session\s*\(\s*\{/,
      /req\.session\.\w+\s*=/,
      /req\.session\.destroy\s*\(/,
    ],
  },
  {
    name: 'cookie-session',
    displayName: 'cookie-session',
    description: 'Cookie-based session middleware for Express',
    type: 'library',
    docsUrl: 'https://github.com/expressjs/cookie-session',
    flowType: 'session',
    importPatterns: [
      /require\s*\(\s*['"]cookie-session['"]\s*\)/,
      /from\s+['"]cookie-session['"]/,
    ],
    usagePatterns: [/cookieSession\s*\(\s*\{/],
  },
  {
    name: '@simplewebauthn/server',
    displayName: 'SimpleWebAuthn (Server)',
    description: 'Comprehensive WebAuthn/FIDO2 server-side library',
    type: 'library',
    docsUrl: 'https://simplewebauthn.dev',
    flowType: 'webauthn',
    importPatterns: [
      /require\s*\(\s*['"]@simplewebauthn\/server['"]\s*\)/,
      /from\s+['"]@simplewebauthn\/server['"]/,
    ],
    usagePatterns: [
      /generateRegistrationOptions\s*\(/,
      /verifyRegistrationResponse\s*\(/,
      /generateAuthenticationOptions\s*\(/,
      /verifyAuthenticationResponse\s*\(/,
    ],
  },
  {
    name: '@simplewebauthn/browser',
    displayName: 'SimpleWebAuthn (Browser)',
    description: 'WebAuthn browser-side helper library',
    type: 'library',
    docsUrl: 'https://simplewebauthn.dev',
    flowType: 'webauthn',
    importPatterns: [
      /require\s*\(\s*['"]@simplewebauthn\/browser['"]\s*\)/,
      /from\s+['"]@simplewebauthn\/browser['"]/,
    ],
    usagePatterns: [
      /startRegistration\s*\(/,
      /startAuthentication\s*\(/,
    ],
  },
  {
    name: 'fido2-lib',
    displayName: 'fido2-lib',
    description: 'FIDO2/WebAuthn server library for Node.js',
    type: 'library',
    docsUrl: 'https://github.com/webauthn-open-source/fido2-lib',
    flowType: 'webauthn',
    importPatterns: [
      /require\s*\(\s*['"]fido2-lib['"]\s*\)/,
      /from\s+['"]fido2-lib['"]/,
    ],
    usagePatterns: [
      /new\s+Fido2Lib\s*\(/,
      /\.attestationOptions\s*\(/,
      /\.attestationResult\s*\(/,
      /\.assertionOptions\s*\(/,
      /\.assertionResult\s*\(/,
    ],
  },
  {
    name: 'bcrypt',
    displayName: 'bcrypt',
    description: 'Password hashing library using bcrypt algorithm',
    type: 'library',
    docsUrl: 'https://github.com/kelektiv/node.bcrypt.js',
    flowType: 'unknown',
    importPatterns: [
      /require\s*\(\s*['"]bcrypt(?:js)?['"]\s*\)/,
      /from\s+['"]bcrypt(?:js)?['"]/,
    ],
    usagePatterns: [
      /bcrypt\.hash\s*\(/,
      /bcrypt\.compare\s*\(/,
      /bcrypt\.hashSync\s*\(/,
      /bcrypt\.compareSync\s*\(/,
    ],
  },
  {
    name: 'argon2',
    displayName: 'Argon2',
    description: 'Password hashing using the Argon2 algorithm (winner of Password Hashing Competition)',
    type: 'library',
    docsUrl: 'https://github.com/ranisalt/node-argon2',
    flowType: 'unknown',
    importPatterns: [
      /require\s*\(\s*['"]argon2['"]\s*\)/,
      /from\s+['"]argon2['"]/,
    ],
    usagePatterns: [
      /argon2\.hash\s*\(/,
      /argon2\.verify\s*\(/,
    ],
  },
  {
    name: 'csrf',
    displayName: 'CSRF Protection',
    description: 'Cross-Site Request Forgery protection middleware',
    type: 'library',
    docsUrl: 'https://github.com/pillarjs/csrf',
    flowType: 'unknown',
    importPatterns: [
      /require\s*\(\s*['"](?:csrf|csurf)['"]\s*\)/,
      /from\s+['"](?:csrf|csurf)['"]/,
    ],
    usagePatterns: [/csurf\s*\(/, /csrf\s*\(/],
  },

  // ---- Python libraries ----
  {
    name: 'flask',
    displayName: 'Flask',
    description: 'Lightweight Python web framework',
    type: 'framework',
    docsUrl: 'https://flask.palletsprojects.com',
    flowType: 'session',
    importPatterns: [
      /from\s+flask\s+import/,
      /^import\s+flask\b/m,
    ],
    usagePatterns: [
      /Flask\s*\(\s*__name__/,
      /app\.route\s*\(/,
      /Blueprint\s*\(/,
      /session\[/,
      /request\.json/,
    ],
  },
  {
    name: 'flask-cors',
    displayName: 'Flask-CORS',
    description: 'Cross-Origin Resource Sharing for Flask',
    type: 'library',
    docsUrl: 'https://flask-cors.readthedocs.io',
    flowType: 'unknown',
    importPatterns: [
      /from\s+flask_cors\s+import/,
      /import\s+flask_cors/,
    ],
    usagePatterns: [
      /CORS\s*\(/,
      /cross_origin\s*\(/,
    ],
  },
  {
    name: 'pyjwt',
    displayName: 'PyJWT',
    description: 'JSON Web Token implementation for Python',
    type: 'library',
    docsUrl: 'https://pyjwt.readthedocs.io',
    flowType: 'jwt',
    importPatterns: [
      /^import\s+jwt\b/m,
      /from\s+jwt\s+import/,
    ],
    usagePatterns: [
      /jwt\.encode\s*\(/,
      /jwt\.decode\s*\(/,
    ],
  },
  {
    name: 'python-jose',
    displayName: 'python-jose',
    description: 'JOSE (JWT/JWE/JWS/JWK) implementation for Python',
    type: 'library',
    docsUrl: 'https://python-jose.readthedocs.io',
    flowType: 'jwt',
    importPatterns: [
      /from\s+jose\s+import/,
      /from\s+jose\.jwt\s+import/,
    ],
    usagePatterns: [
      /jwt\.encode\s*\(/,
      /jwt\.decode\s*\(/,
    ],
  },
  {
    name: 'flask-jwt-extended',
    displayName: 'Flask-JWT-Extended',
    description: 'JWT authentication for Flask applications',
    type: 'library',
    docsUrl: 'https://flask-jwt-extended.readthedocs.io',
    flowType: 'jwt',
    importPatterns: [
      /from\s+flask_jwt_extended\s+import/,
      /import\s+flask_jwt_extended/,
    ],
    usagePatterns: [
      /create_access_token\s*\(/,
      /create_refresh_token\s*\(/,
      /@jwt_required/,
      /get_jwt_identity\s*\(/,
      /verify_jwt_in_request\s*\(/,
    ],
  },
  {
    name: 'django-auth',
    displayName: 'Django Authentication',
    description: 'Django built-in authentication framework',
    type: 'framework',
    docsUrl: 'https://docs.djangoproject.com/en/stable/topics/auth/',
    flowType: 'session',
    importPatterns: [
      /from\s+django\.contrib\.auth\s+import/,
      /from\s+django\.contrib\.auth\.decorators\s+import/,
      /from\s+django\.contrib\.auth\.mixins\s+import/,
    ],
    usagePatterns: [
      /authenticate\s*\(/,
      /login\s*\(\s*request/,
      /logout\s*\(\s*request/,
      /@login_required/,
      /LoginRequiredMixin/,
      /check_password\s*\(/,
    ],
  },
  {
    name: 'djangorestframework-simplejwt',
    displayName: 'Simple JWT (DRF)',
    description: 'JWT authentication for Django REST Framework',
    type: 'library',
    docsUrl: 'https://django-rest-framework-simplejwt.readthedocs.io',
    flowType: 'jwt',
    importPatterns: [
      /from\s+rest_framework_simplejwt\s+import/,
      /from\s+rest_framework_simplejwt\.tokens\s+import/,
    ],
    usagePatterns: [
      /RefreshToken\.for_user\s*\(/,
      /AccessToken\s*\(/,
      /TokenObtainPairView/,
    ],
  },
  {
    name: 'django-allauth',
    displayName: 'django-allauth',
    description: 'Integrated OAuth/social authentication for Django',
    type: 'library',
    docsUrl: 'https://django-allauth.readthedocs.io',
    flowType: 'oauth2',
    importPatterns: [
      /from\s+allauth\s+import/,
      /from\s+allauth\.socialaccount\s+import/,
    ],
    usagePatterns: [
      /SocialAccount\s*\(/,
      /allauth\.account/,
    ],
  },
  {
    name: 'authlib',
    displayName: 'Authlib',
    description: 'OAuth 1.0/2.0 and OpenID Connect library for Python',
    type: 'library',
    docsUrl: 'https://docs.authlib.org',
    flowType: 'oauth2',
    importPatterns: [
      /from\s+authlib\s+import/,
      /from\s+authlib\.integrations\s+import/,
      /import\s+authlib/,
    ],
    usagePatterns: [
      /OAuth2Session\s*\(/,
      /FlaskOAuth\s*\(/,
      /StarletteOAuth2App/,
    ],
  },
  {
    name: 'flask-login',
    displayName: 'Flask-Login',
    description: 'Session-based user authentication for Flask',
    type: 'library',
    docsUrl: 'https://flask-login.readthedocs.io',
    flowType: 'session',
    importPatterns: [
      /from\s+flask_login\s+import/,
      /import\s+flask_login/,
    ],
    usagePatterns: [
      /login_user\s*\(/,
      /logout_user\s*\(/,
      /@login_required/,
      /current_user\./,
      /LoginManager\s*\(/,
    ],
  },
  {
    name: 'fastapi-security',
    displayName: 'FastAPI Security',
    description: 'Built-in OAuth2/JWT security utilities for FastAPI',
    type: 'framework',
    docsUrl: 'https://fastapi.tiangolo.com/tutorial/security/',
    flowType: 'oauth2',
    importPatterns: [
      /from\s+fastapi\.security\s+import/,
      /from\s+fastapi\s+import.*\bDepends\b/,
    ],
    usagePatterns: [
      /OAuth2PasswordBearer\s*\(/,
      /OAuth2PasswordRequestForm/,
      /Depends\s*\(\s*get_current_user/,
      /Security\s*\(\s*\w/,
    ],
  },
  {
    name: 'passlib',
    displayName: 'passlib',
    description: 'Comprehensive password hashing library for Python',
    type: 'library',
    docsUrl: 'https://passlib.readthedocs.io',
    flowType: 'unknown',
    importPatterns: [
      /from\s+passlib\s+import/,
      /from\s+passlib\.hash\s+import/,
      /from\s+passlib\.context\s+import/,
    ],
    usagePatterns: [
      /CryptContext\s*\(/,
      /\.hash\s*\(/,
      /\.verify\s*\(/,
      /bcrypt\.hash\s*\(/,
      /argon2\.hash\s*\(/,
    ],
  },
  {
    name: 'py-bcrypt',
    displayName: 'bcrypt (Python)',
    description: 'bcrypt password hashing for Python',
    type: 'library',
    docsUrl: 'https://github.com/pyca/bcrypt',
    flowType: 'unknown',
    importPatterns: [
      /^import\s+bcrypt\b/m,
      /from\s+bcrypt\s+import/,
    ],
    usagePatterns: [
      /bcrypt\.hashpw\s*\(/,
      /bcrypt\.checkpw\s*\(/,
      /bcrypt\.gensalt\s*\(/,
    ],
  },
  {
    name: 'py-webauthn',
    displayName: 'py_webauthn',
    description: 'WebAuthn/FIDO2 server-side library for Python',
    type: 'library',
    docsUrl: 'https://github.com/duo-labs/py_webauthn',
    flowType: 'webauthn',
    importPatterns: [
      /^import\s+webauthn\b/m,
      /from\s+webauthn\s+import/,
      /from\s+webauthn\.helpers\b/,       // from webauthn.helpers.cose import ...
      /from\s+webauthn\.helpers\.structs\s+import/,
      /from\s+webauthn\.helpers\.cose\s+import/,
      /from\s+webauthn\.helpers\.exceptions\s+import/,
    ],
    usagePatterns: [
      /generate_registration_options\s*\(/,
      /verify_registration_response\s*\(/,
      /generate_authentication_options\s*\(/,
      /verify_authentication_response\s*\(/,
      /options_to_json\s*\(/,
      /base64url_to_bytes\s*\(/,
    ],
  },
  {
    name: 'fido2',
    displayName: 'python-fido2',
    description: 'FIDO2/WebAuthn server library for Python',
    type: 'library',
    docsUrl: 'https://github.com/Yubico/python-fido2',
    flowType: 'webauthn',
    importPatterns: [
      /from\s+fido2\s+import/,
      /from\s+fido2\.server\s+import/,
      /from\s+fido2\.webauthn\s+import/,
    ],
    usagePatterns: [
      /Fido2Server\s*\(/,
      /register_begin\s*\(/,
      /register_complete\s*\(/,
      /authenticate_begin\s*\(/,
      /authenticate_complete\s*\(/,
    ],
  },
  {
    name: 'itsdangerous',
    displayName: 'itsdangerous',
    description: 'Cryptographic token signing library used by Flask for sessions',
    type: 'library',
    docsUrl: 'https://itsdangerous.palletsprojects.com',
    flowType: 'session',
    importPatterns: [
      /from\s+itsdangerous\s+import/,
      /import\s+itsdangerous/,
    ],
    usagePatterns: [
      /TimedSerializer\s*\(/,
      /URLSafeTimedSerializer\s*\(/,
      /\.dumps\s*\(/,
      /\.loads\s*\(/,
    ],
  },

  // ---- Java / Kotlin libraries ----
  {
    name: 'spring-security',
    displayName: 'Spring Security',
    description: 'Comprehensive authentication and authorization framework for Java/Spring applications',
    type: 'framework',
    docsUrl: 'https://spring.io/projects/spring-security',
    flowType: 'session',
    importPatterns: [
      /import\s+org\.springframework\.security\./,
      /@EnableWebSecurity/,
      /@EnableMethodSecurity/,
      /SecurityFilterChain/,
    ],
    usagePatterns: [
      /\.authorizeHttpRequests\s*\(/,
      /\.formLogin\s*\(/,
      /\.httpBasic\s*\(/,
      /SecurityContextHolder\./,
      /Authentication\s+\w+\s*=/,
    ],
  },
  {
    name: 'spring-security-oauth2',
    displayName: 'Spring Security OAuth2',
    description: 'OAuth2 resource server and client support for Spring Security',
    type: 'library',
    docsUrl: 'https://spring.io/projects/spring-security',
    flowType: 'oauth2',
    importPatterns: [
      /import\s+org\.springframework\.security\.oauth2\./,
      /@EnableAuthorizationServer/,
      /@EnableResourceServer/,
      /NimbusJwtDecoder/,
      /JwtDecoder/,
    ],
    usagePatterns: [
      /\.oauth2ResourceServer\s*\(/,
      /\.oauth2Login\s*\(/,
      /OidcUserService\s*/,
      /NimbusJwtDecoder\.withJwkSetUri/,
    ],
  },
  {
    name: 'jjwt',
    displayName: 'JJWT (Java JWT)',
    description: 'JSON Web Token library for Java by jwtk',
    type: 'library',
    docsUrl: 'https://github.com/jwtk/jjwt',
    flowType: 'jwt',
    importPatterns: [
      /import\s+io\.jsonwebtoken\./,
    ],
    usagePatterns: [
      /Jwts\.builder\s*\(\)/,
      /Jwts\.parser(?:Builder)?\s*\(\)/,
      /\.signWith\s*\(/,
      /\.parseClaimsJws\s*\(/,
      /\.parseClaimsJwt\s*\(/,
    ],
  },
  {
    name: 'java-jwt',
    displayName: 'Auth0 Java JWT',
    description: 'JWT implementation for Java by Auth0',
    type: 'library',
    docsUrl: 'https://github.com/auth0/java-jwt',
    flowType: 'jwt',
    importPatterns: [
      /import\s+com\.auth0\.jwt\./,
    ],
    usagePatterns: [
      /JWT\.create\s*\(\)/,
      /JWT\.require\s*\(/,
      /\.sign\s*\(\s*Algorithm\./,
      /\.verify\s*\(\s*\w*[Tt]oken/,
    ],
  },
  {
    name: 'nimbus-jose-jwt',
    displayName: 'Nimbus JOSE+JWT',
    description: 'Full-featured JOSE and JWT library for Java',
    type: 'library',
    docsUrl: 'https://connect2id.com/products/nimbus-jose-jwt',
    flowType: 'jwt',
    importPatterns: [
      /import\s+com\.nimbusds\.jwt\./,
      /import\s+com\.nimbusds\.jose\./,
    ],
    usagePatterns: [
      /SignedJWT\.parse\s*\(/,
      /new\s+JWTClaimsSet\s*\./,
      /JWSSigner\b/,
      /JWSVerifier\b/,
    ],
  },
  {
    name: 'apache-shiro',
    displayName: 'Apache Shiro',
    description: 'Java security framework for authentication, authorization, and session management',
    type: 'framework',
    docsUrl: 'https://shiro.apache.org',
    flowType: 'session',
    importPatterns: [
      /import\s+org\.apache\.shiro\./,
    ],
    usagePatterns: [
      /SecurityUtils\.getSubject\s*\(\)/,
      /subject\.login\s*\(/,
      /subject\.isAuthenticated\s*\(\)/,
      /UsernamePasswordToken\s*\(/,
    ],
  },
  {
    name: 'keycloak-spring',
    displayName: 'Keycloak (Spring)',
    description: 'Keycloak adapter for Spring Boot / Spring Security',
    type: 'library',
    docsUrl: 'https://www.keycloak.org/docs/latest/securing_apps/',
    flowType: 'oauth2',
    importPatterns: [
      /import\s+org\.keycloak\./,
      /@KeycloakConfiguration/,
    ],
    usagePatterns: [
      /KeycloakSecurityContext\b/,
      /keycloak\.token\./,
      /KeycloakSpringBootConfigResolver/,
    ],
  },
  {
    name: 'webauthn4j',
    displayName: 'WebAuthn4J',
    description: 'WebAuthn/FIDO2 server-side library for Java',
    type: 'library',
    docsUrl: 'https://webauthn4j.github.io/webauthn4j',
    flowType: 'webauthn',
    importPatterns: [
      /import\s+com\.webauthn4j\./,
    ],
    usagePatterns: [
      /WebAuthnManager\b/,
      /RegistrationData\b/,
      /AuthenticationData\b/,
    ],
  },
  {
    name: 'yubico-webauthn',
    displayName: 'Yubico WebAuthn Server',
    description: "Yubico's java-webauthn-server library for WebAuthn/FIDO2",
    type: 'library',
    docsUrl: 'https://github.com/Yubico/java-webauthn-server',
    flowType: 'webauthn',
    importPatterns: [
      /import\s+com\.yubico\.webauthn\./,
    ],
    usagePatterns: [
      /RelyingParty\./,
      /\.startRegistration\s*\(/,
      /\.finishRegistration\s*\(/,
      /\.startAssertion\s*\(/,
      /\.finishAssertion\s*\(/,
    ],
  },
  {
    name: 'spring-security-crypto',
    displayName: 'Spring BCryptPasswordEncoder',
    description: 'Password encoding via Spring Security Crypto (BCrypt, Argon2, SCrypt, PBKDF2)',
    type: 'library',
    docsUrl: 'https://docs.spring.io/spring-security/reference/features/authentication/password-storage.html',
    flowType: 'unknown',
    importPatterns: [
      /import\s+org\.springframework\.security\.crypto\.bcrypt\./,
      /import\s+org\.springframework\.security\.crypto\.password\./,
      /BCryptPasswordEncoder/,
      /Argon2PasswordEncoder/,
      /SCryptPasswordEncoder/,
      /PBKDF2PasswordEncoder/,
    ],
    usagePatterns: [
      /new\s+BCryptPasswordEncoder\s*\(/,
      /passwordEncoder\.encode\s*\(/,
      /passwordEncoder\.matches\s*\(/,
    ],
  },
];

export const VULNERABILITY_PATTERNS: VulnerabilityPattern[] = [
  {
    id: 'HARDCODED_SECRET',
    title: 'Hardcoded Secret or Credential',
    description: 'A secret key, password, or credential appears to be hardcoded directly in source code. This exposes credentials to anyone with repository access and makes rotation difficult.',
    recommendation: 'Move all secrets to environment variables (process.env.SECRET_KEY) or a secrets management service like HashiCorp Vault, AWS Secrets Manager, or Azure Key Vault.',
    severity: 'critical',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-798',
    pattern: /(?:secret|password|passwd|api[_-]?key|apikey|auth[_-]?token|private[_-]?key|access[_-]?token)\s*[:=]\s*['"`][a-zA-Z0-9+/=@#$%^&*!_\-]{6,}['"`]/gi,
    excludePatterns: [
      /process\.env\./,
      /config\.\w+/,
      /process\.env\[/,
      /placeholder/i,
      /your[_-]?(?:secret|key|token)/i,
      /example/i,
      /\<\w+\>/,
    ],
    references: ['https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_credentials'],
  },
  {
    id: 'JWT_NONE_ALGORITHM',
    title: 'JWT "none" Algorithm Permitted',
    description: 'The JWT verification configuration includes "none" in the allowed algorithms list. This allows attackers to forge tokens by setting alg:none in the header and omitting the signature.',
    recommendation: 'Remove "none" from the algorithms list. Always explicitly specify the expected algorithm (e.g., ["HS256"]) and validate it before processing.',
    severity: 'critical',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-347',
    pattern: /algorithms\s*:\s*\[[^\]]*['"]none['"][^\]]*\]/gi,
    references: ['https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/'],
  },
  {
    id: 'JWT_DECODE_NO_VERIFY',
    title: 'JWT Decoded Without Signature Verification',
    description: 'jwt.decode() is used which does NOT verify the token signature. An attacker can modify the payload and bypass authorization checks if this decoded data is trusted.',
    recommendation: 'Replace jwt.decode() with jwt.verify() providing the correct secret or public key. Only use jwt.decode() for inspecting public token metadata.',
    severity: 'high',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-347',
    pattern: /jwt\.decode\s*\([^)]*\)/g,
    excludePatterns: [/\/\/.*jwt\.decode/, /\*.*jwt\.decode/],
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html'],
  },
  {
    id: 'WEAK_PASSWORD_HASH',
    title: 'Weak Algorithm Used for Password Hashing',
    description: 'MD5 or SHA-1 is being used for hashing, which is cryptographically broken and unsuitable for password storage. These algorithms are fast by design, making brute-force attacks trivial.',
    recommendation: 'Use a password-specific hashing algorithm: bcrypt (cost factor ≥12), Argon2id, or scrypt. These are intentionally slow and include salting.',
    severity: 'high',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-916',
    pattern: /(?:createHash\s*\(\s*['"](?:md5|sha1)['"]|md5\s*\(|sha1\s*\()/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'INSECURE_COOKIE',
    title: 'Cookie Missing Security Flags',
    description: 'A cookie is being set without one or more critical security attributes. Missing httpOnly allows JavaScript access (XSS risk); missing secure allows transmission over HTTP; missing sameSite enables CSRF attacks.',
    recommendation: 'For session/auth cookies, set: { httpOnly: true, secure: true, sameSite: "strict" }. The "secure" flag is critical in production.',
    severity: 'medium',
    owasp: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-614',
    pattern: /res\.cookie\s*\(\s*['"][^'"]+['"]\s*,\s*[^,]+(?:,\s*\{[^}]*\})?\s*\)/g,
    checkFn: (content: string, match: RegExpMatchArray): boolean => {
      const cookieCall = match[0];
      const hasOptions = cookieCall.includes('{');
      if (!hasOptions) return true;
      return !cookieCall.includes('httpOnly') || !cookieCall.includes('secure') || !cookieCall.includes('sameSite');
    },
    references: ['https://owasp.org/www-community/controls/SecureCookieAttribute'],
  },
  {
    id: 'SESSION_NO_SECRET',
    title: 'Session Configured With Weak or Missing Secret',
    description: 'The session secret appears to be hardcoded or uses a weak default value. A compromised session secret allows forging session tokens.',
    recommendation: 'Generate a cryptographically random secret of at least 32 bytes and store it in an environment variable.',
    severity: 'high',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-798',
    pattern: /session\s*\(\s*\{[^}]*secret\s*:\s*['"`][a-zA-Z0-9]{1,20}['"`]/gi,
    excludePatterns: [/process\.env\./, /config\./],
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html'],
  },
  {
    id: 'MISSING_CSRF',
    title: 'Auth Endpoint May Lack CSRF Protection',
    description: 'A state-changing authentication endpoint (login, logout, register) was detected without obvious CSRF protection. Cross-site request forgery can force authenticated actions.',
    recommendation: 'Use the csurf middleware or implement double-submit cookie pattern. For SPAs using JWTs in Authorization headers, CSRF is mitigated by same-origin restrictions.',
    severity: 'medium',
    owasp: 'A01:2021 – Broken Access Control',
    cwe: 'CWE-352',
    pattern: /router\.post\s*\(\s*['"]\/(?:login|logout|register|signup|auth)['"]/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html'],
  },
  {
    id: 'JWT_NO_EXPIRY',
    title: 'JWT Created Without Expiration',
    description: 'A JWT is being signed without an "exp" (expiration) claim. Non-expiring tokens remain valid indefinitely, making compromise permanent until the signing key is rotated.',
    recommendation: 'Always set an appropriate expiration: jwt.sign(payload, secret, { expiresIn: "1h" }). Use short-lived access tokens with refresh token rotation.',
    severity: 'medium',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-613',
    pattern: /jwt\.sign\s*\(\s*[^,]+,\s*[^,)]+\s*\)/g,
    checkFn: (content: string, match: RegExpMatchArray): boolean => {
      const call = match[0];
      return !call.includes('expiresIn') && !call.includes('exp:') && !call.includes('"exp"');
    },
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html'],
  },
  {
    id: 'WEBAUTHN_MISSING_ORIGIN_CHECK',
    title: 'WebAuthn Missing Origin Validation',
    description: 'WebAuthn verification may not validate the expected origin, which allows an attacker to redirect a legitimate authentication attempt to a malicious site.',
    recommendation: 'Always specify the expectedOrigin parameter in verifyRegistrationResponse and verifyAuthenticationResponse. It should be the exact origin (e.g., "https://example.com").',
    severity: 'high',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-346',
    pattern: /verify(?:Registration|Authentication)Response\s*\(\s*\{[^}]*\}\s*\)/g,
    checkFn: (content: string, match: RegExpMatchArray): boolean => {
      return !match[0].includes('expectedOrigin') && !match[0].includes('origin');
    },
    references: ['https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential'],
  },
  {
    id: 'WEBAUTHN_PREDICTABLE_CHALLENGE',
    title: 'WebAuthn Challenge May Not Be Sufficiently Random',
    description: 'The WebAuthn challenge must be cryptographically random and at least 16 bytes to prevent replay attacks. Using Math.random() or short challenges is dangerous.',
    recommendation: 'Use crypto.randomBytes(32) or an equivalent cryptographically secure random number generator. The SimpleWebAuthn library generates challenges automatically.',
    severity: 'critical',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-338',
    pattern: /challenge\s*:\s*(?:Math\.random|Buffer\.from\s*\(\s*['"][a-zA-Z0-9]{1,16}['"])/g,
    references: ['https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-challenge'],
  },
  {
    id: 'SQL_INJECTION_AUTH',
    title: 'Potential SQL Injection in Authentication Query',
    description: 'String interpolation or concatenation is being used in what appears to be an authentication SQL query. This can allow SQL injection to bypass authentication entirely.',
    recommendation: 'Use parameterized queries or prepared statements. Never concatenate user input directly into SQL strings.',
    severity: 'critical',
    owasp: 'A03:2021 – Injection',
    cwe: 'CWE-89',
    pattern: /(?:SELECT|select)\s+.+(?:WHERE|where)\s+.+(?:username|email|user)\s*=\s*[`'"]\s*\$\{/g,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
  },
  {
    id: 'PLAINTEXT_PASSWORD_COMPARE',
    title: 'Password Compared in Plain Text',
    description: 'A password comparison is performed without using a timing-safe comparison or password hashing. This is vulnerable to timing attacks and stores passwords in plain text.',
    recommendation: 'Hash passwords with bcrypt or Argon2 at registration. At login, use bcrypt.compare() or argon2.verify() which are timing-safe by design.',
    severity: 'critical',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-256',
    pattern: /(?:password|passwd)\s*===?\s*(?:req\.body|user\.|stored)/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'VERBOSE_AUTH_ERROR',
    title: 'Verbose Authentication Error Messages',
    description: 'Authentication error messages may reveal whether an account exists or why login failed, enabling user enumeration attacks.',
    recommendation: 'Return generic error messages like "Invalid credentials" regardless of whether the user exists or the password is wrong.',
    severity: 'low',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-204',
    pattern: /(?:res\.(?:status|json|send))[^;]*(?:user not found|no such user|account does not exist|wrong password|incorrect password)/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html'],
  },

  // ---- Python-specific vulnerability patterns ----
  {
    id: 'PYTHON_JWT_NO_VERIFY',
    title: 'PyJWT Decoded With Signature Verification Disabled',
    description: 'jwt.decode() is called with options={"verify_signature": False} or algorithms=["none"], bypassing signature validation entirely.',
    recommendation: 'Remove verify_signature: False and always pass the correct secret and expected algorithms: jwt.decode(token, key, algorithms=["HS256"]).',
    severity: 'critical',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-347',
    pattern: /jwt\.decode\s*\([^)]*(?:verify_signature['"]\s*:\s*False|algorithms\s*=\s*\[\s*['"]none['"])/gi,
    references: ['https://pyjwt.readthedocs.io/en/stable/usage.html#encoding-decoding-tokens-with-hs256'],
  },
  {
    id: 'PYTHON_WEAK_HASH',
    title: 'Weak Hash Algorithm Used (Python hashlib)',
    description: 'hashlib.md5() or hashlib.sha1() is used, which are cryptographically broken and unsuitable for password storage or integrity-sensitive operations.',
    recommendation: 'For password hashing use bcrypt, Argon2 (argon2-cffi), or passlib. For non-password integrity use hashlib.sha256() or higher.',
    severity: 'high',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-916',
    pattern: /hashlib\.(?:md5|sha1)\s*\(/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'PYTHON_HARDCODED_SECRET',
    title: 'Hardcoded Secret in Python Code',
    description: 'A Django SECRET_KEY, Flask secret_key, JWT secret, or API key appears to be hardcoded. This exposes credentials to anyone with code access.',
    recommendation: 'Load secrets from environment variables: SECRET_KEY = os.environ.get("SECRET_KEY") or use python-decouple / django-environ.',
    severity: 'critical',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-798',
    pattern: /(?:SECRET_KEY|secret_key|JWT_SECRET|API_KEY|PRIVATE_KEY|CLIENT_SECRET)\s*=\s*['"][a-zA-Z0-9+/=@#$%^&*!_\-]{8,}['"]/g,
    excludePatterns: [
      /os\.environ/,
      /os\.getenv/,
      /config\(/,
      /env\(/,
      /decouple/,
      /django-insecure-/,
    ],
    references: ['https://docs.djangoproject.com/en/stable/ref/settings/#secret-key'],
  },
  {
    id: 'DJANGO_INSECURE_KEY',
    title: 'Django Default Insecure SECRET_KEY In Use',
    description: 'The Django SECRET_KEY still uses the default "django-insecure-" prefix generated by startproject. This key is not secret and should be replaced before any deployment.',
    recommendation: 'Generate a new key with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())" and store it in an environment variable.',
    severity: 'critical',
    owasp: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-798',
    pattern: /SECRET_KEY\s*=\s*['"]django-insecure-[^'"]+['"]/g,
    references: ['https://docs.djangoproject.com/en/stable/ref/settings/#secret-key'],
  },
  {
    id: 'DJANGO_DEBUG_TRUE',
    title: 'Django DEBUG = True in Settings',
    description: 'Django DEBUG mode is enabled. In production this exposes full stack traces, environment variables, and installed app details to any visitor who triggers an error.',
    recommendation: 'Set DEBUG = False in production. Use environment variables: DEBUG = os.environ.get("DEBUG", "False") == "True".',
    severity: 'high',
    owasp: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-215',
    pattern: /^\s*DEBUG\s*=\s*True\b/gm,
    references: ['https://docs.djangoproject.com/en/stable/ref/settings/#debug'],
  },
  {
    id: 'PYTHON_SQL_INJECTION_AUTH',
    title: 'Potential SQL Injection in Python Auth Query',
    description: 'String formatting or concatenation is used to build an authentication SQL query, which is exploitable via SQL injection to bypass authentication.',
    recommendation: 'Use parameterized queries: cursor.execute("SELECT * FROM users WHERE username = %s", (username,)) — never use % or f-strings in SQL.',
    severity: 'critical',
    owasp: 'A03:2021 – Injection',
    cwe: 'CWE-89',
    pattern: /(?:execute|raw)\s*\(\s*(?:f['"]|['"].*%\s*(?:username|email|user|password)|\+\s*(?:username|email|user))/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
  },
  {
    id: 'PYTHON_PLAINTEXT_PASSWORD',
    title: 'Password Compared in Plain Text (Python)',
    description: 'A password is compared using == or string equality instead of a secure constant-time comparison or hashed password check.',
    recommendation: 'Use bcrypt.checkpw(), passlib verify(), or Django check_password() — never compare passwords with ==.',
    severity: 'critical',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-256',
    pattern: /(?:password|passwd)\s*==\s*(?:user\.|stored_|db_|request\.)/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'PYTHON_FLASK_NO_SECURE_COOKIE',
    title: 'Flask Session Cookie Missing Security Configuration',
    description: 'Flask session cookies may be transmitted over HTTP or accessible to JavaScript if SESSION_COOKIE_SECURE and SESSION_COOKIE_HTTPONLY are not set.',
    recommendation: 'In your Flask config set: SESSION_COOKIE_SECURE = True, SESSION_COOKIE_HTTPONLY = True, SESSION_COOKIE_SAMESITE = "Lax".',
    severity: 'medium',
    owasp: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-614',
    pattern: /SESSION_COOKIE_SECURE\s*=\s*False/g,
    references: ['https://flask.palletsprojects.com/en/stable/security/#set-cookie-options'],
  },
  {
    id: 'PYTHON_BCRYPT_LOW_ROUNDS',
    title: 'bcrypt Work Factor Too Low (Python)',
    description: 'A bcrypt rounds/cost factor below 12 is used, making it faster to brute-force offline if the database is breached.',
    recommendation: 'Use a minimum of 12 rounds: bcrypt.hashpw(password, bcrypt.gensalt(rounds=12)). Higher is slower but more secure.',
    severity: 'medium',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-916',
    pattern: /gensalt\s*\(\s*(?:rounds\s*=\s*)?([1-9]|1[01])\s*\)/g,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'PYTHON_VERBOSE_AUTH_ERROR',
    title: 'Verbose Authentication Error (Python)',
    description: 'A Python auth handler returns specific error messages that reveal whether a user exists, enabling user enumeration.',
    recommendation: 'Always return a generic "Invalid credentials" message regardless of whether the user was found or the password was wrong.',
    severity: 'low',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-204',
    pattern: /(?:return|raise|jsonify)\s*[^;#\n]*(?:user.?not.?found|no.?such.?user|account.?does.?not.?exist|wrong.?password|incorrect.?password)/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html'],
  },

  // ---- Java-specific vulnerability patterns ----
  {
    id: 'JAVA_HARDCODED_SECRET',
    title: 'Hardcoded Secret in Java/Kotlin Code',
    description: 'A JWT secret, password, or API key appears to be hardcoded in Java/Kotlin source code. Hardcoded secrets are accessible to anyone with code access and cannot be rotated without a deploy.',
    recommendation: 'Load secrets from environment variables (System.getenv("JWT_SECRET")) or Spring @Value("${jwt.secret}") bound to external config.',
    severity: 'critical',
    owasp: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-798',
    pattern: /(?:String|private|final|static)\s+\w*(?:[Ss]ecret|[Pp]assword|[Kk]ey|[Tt]oken|[Aa]pi[Kk]ey)\w*\s*=\s*"[a-zA-Z0-9+/=@#$%^&*!_\-]{8,}"/g,
    excludePatterns: [/System\.getenv|@Value|getProperty|config\./],
    references: ['https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_credentials'],
  },
  {
    id: 'JAVA_MD5_SHA1',
    title: 'Weak Hash Algorithm (Java MessageDigest)',
    description: 'MessageDigest.getInstance("MD5") or "SHA-1" is used. These are cryptographically broken and must not be used for passwords or security-sensitive data.',
    recommendation: 'For passwords use BCryptPasswordEncoder, Argon2PasswordEncoder, or SCryptPasswordEncoder. For integrity checks use SHA-256 minimum.',
    severity: 'high',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-916',
    pattern: /MessageDigest\.getInstance\s*\(\s*"(?:MD5|SHA-1|SHA1)"\s*\)/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  },
  {
    id: 'JAVA_INSECURE_RANDOM',
    title: 'Insecure Random in Security Context (java.util.Random)',
    description: 'java.util.Random is not cryptographically secure and must not be used to generate tokens, challenges, session IDs, or other security-sensitive values.',
    recommendation: 'Replace with java.security.SecureRandom for all security-sensitive random generation.',
    severity: 'high',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-338',
    pattern: /new\s+Random\s*\(\s*\)/g,
    excludePatterns: [/SecureRandom/, /\/\/\s*(?:test|mock|not.*security)/i],
    references: ['https://docs.oracle.com/en/java/docs/api/java.base/java/security/SecureRandom.html'],
  },
  {
    id: 'JAVA_SQL_INJECTION_AUTH',
    title: 'Potential SQL Injection in Java Auth Query',
    description: 'String concatenation is used to build an authentication SQL query. This can be exploited via SQL injection to bypass authentication entirely.',
    recommendation: 'Use PreparedStatement with parameterized queries: ps.setString(1, username) — never concatenate user input into SQL strings.',
    severity: 'critical',
    owasp: 'A03:2021 – Injection',
    cwe: 'CWE-89',
    pattern: /"(?:SELECT|INSERT|UPDATE)\s[^"]*(?:WHERE|VALUES)[^"]*"\s*\+\s*\w/gi,
    references: ['https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
  },
  {
    id: 'JJWT_WEAK_KEY',
    title: 'JWT Signed With Potentially Weak Key (JJWT)',
    description: 'Jwts.builder() .signWith() is called with a string literal key, which may be too short or predictable for secure JWT signing.',
    recommendation: 'Use Keys.secretKeyFor(SignatureAlgorithm.HS256) or an asymmetric RS256/ES256 key pair generated with Keys.keyPairFor().',
    severity: 'medium',
    owasp: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-326',
    pattern: /\.signWith\s*\(\s*(?:SignatureAlgorithm\.\w+\s*,\s*)?["'][a-zA-Z0-9!@#$%^&*]{1,32}["']/g,
    references: ['https://github.com/jwtk/jjwt#creating-a-jwt'],
  },
];

export const AUTH_ROUTE_PATTERNS: RegExp[] = [
  // JS/TS — Express / Fastify
  /router\.(get|post|put|delete|patch)\s*\(\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn|fido)[^'"]*['"]/gi,
  /app\.(get|post|put|delete|patch)\s*\(\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn|fido)[^'"]*['"]/gi,
  /path\s*:\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback)[^'"]*['"]/gi,
  // Python — Flask decorators
  /@(?:app|blueprint|bp|api)\.route\s*\(\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn|fido)[^'"]*['"]/gi,
  /@(?:app|blueprint|bp|api|router)\.(?:get|post|put|delete|patch)\s*\(\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn|fido)[^'"]*['"]/gi,
  // Python — Django URL patterns
  /path\s*\(\s*['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn)[^'"]*['"]/gi,
  /re_path\s*\(\s*r?['"][^'"]*(?:login|logout|auth|register|signup|token|oauth|callback)[^'"]*['"]/gi,
  // Python — FastAPI
  /@(?:app|router|api)\.(?:get|post|put|delete|patch)\s*\(\s*['"][^'"]*(?:login|logout|auth|token|oauth|refresh|verify)[^'"]*['"]/gi,
  // Java/Spring — @RequestMapping, @PostMapping, @GetMapping
  /@(?:Post|Get|Put|Delete|Request)Mapping\s*\(\s*(?:value\s*=\s*)?["'][^"']*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh|passkey|webauthn)[^"']*["']/gi,
  // Java/Spring — @Path (JAX-RS)
  /@Path\s*\(\s*["'][^"']*(?:login|logout|auth|register|signup|token|oauth|callback|verify|refresh)[^"']*["']\s*\)/gi,
];

export const MIDDLEWARE_PATTERNS: RegExp[] = [
  // JS/TS
  /(?:app|router)\.use\s*\(\s*(?:session|passport\.initialize|passport\.session|requireAuth|isAuthenticated|verifyToken|authenticate|checkAuth|jwtAuth)\s*[(),]/g,
  /(?:requireAuth|isAuthenticated|verifyToken|authenticate|checkAuth|jwtAuth|authMiddleware)\s*,/g,
  // Python — decorators and dependency injection
  /@login_required\b/g,
  /@jwt_required\s*\(/g,
  /@permission_required\s*\(/g,
  /Depends\s*\(\s*get_current_user/g,
  /Depends\s*\(\s*get_current_active_user/g,
  /Security\s*\(\s*oauth2_scheme/g,
  /LoginRequiredMixin\b/g,
  /PermissionRequiredMixin\b/g,
  // Java/Spring Security — method-level security annotations
  /@PreAuthorize\s*\(/g,
  /@Secured\s*\(/g,
  /@RolesAllowed\s*\(/g,
  /SecurityContextHolder\.getContext\s*\(\)/g,
  /\.authenticated\s*\(\)/g,
  /\.hasRole\s*\(/g,
  /\.hasAuthority\s*\(/g,
  // Java/Spring — filter chain
  /OncePerRequestFilter/g,
  /UsernamePasswordAuthenticationFilter/g,
  /JwtAuthenticationFilter/g,
];
